// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvjxjbltxqlbqssrrzxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2anhqYmx0eHFsYnFzc3JyenhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzQ0MjUsImV4cCI6MjA2MzUxMDQyNX0.kaR8uqzMv6wVACeyEBGLcSzHd_vIMzITzcEz5TC8Ygg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);